version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./app:/app
    command: sh -c "npm run dev"
    tty: true
    ports:
      - "3000:3000"