import type { NextPage } from "next";
import Head from "next/head";
import { Layout } from "../components/commons/layout/Layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>content</Layout>
    </>
  );
};

export default Home;
